# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main

pool:
  name: Default

variables:
  backendPath: 'Backend'
  aiServicePath: 'ai-service'
  frontendPath: 'patient-monitoring-frontend'

steps:

# Checkout source code
- task: Checkout@1
  displayName: 'Checkout Repository'

# Use Node.js (v18)
- task: UseNode@1
  displayName: 'Set Node.js Version'
  inputs:
    version: '18.x'

# Print directories for debugging
- task: PowerShell@2
  displayName: 'Debug: Show Folder Structure'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Backend path: $(backendPath)"
      Write-Host "AI Service path: $(aiServicePath)"
      Write-Host "Frontend path: $(frontendPath)"
      Get-ChildItem -Recurse

# Install Backend Dependencies
- task: Npm@1
  displayName: 'Install Backend Dependencies'
  inputs:
    workingDir: '$(backendPath)'
    command: 'install'

# Install AI Service Dependencies
- task: Npm@1
  displayName: 'Install AI Service Dependencies'
  inputs:
    workingDir: '$(aiServicePath)'
    command: 'install'

# Install Frontend Dependencies
- task: Npm@1
  displayName: 'Install Frontend Dependencies'
  inputs:
    workingDir: '$(frontendPath)'
    command: 'install'

# Build Frontend (React/Vite)
- task: Npm@1
  displayName: 'Build Frontend Application'
  inputs:
    workingDir: '$(frontendPath)'
    command: 'run'
    arguments: 'build'

# Copy build output for deployment
- task: CopyFiles@2
  displayName: 'Copy Frontend Build to Staging Directory'
  inputs:
    SourceFolder: '$(frontendPath)/dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/frontend-dist'

# Publish frontend build artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Frontend Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend-dist'
    ArtifactName: 'frontend'
    publishLocation: 'Container'
